export const DATA = [
  {
    _key: '5913364683',
    _id: 'biz_customer/5913364683',
    _rev: '_cfg2tGq---',
    customer_id: '1',
    customer_name: 'ALEXCEED',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913364872',
    _id: 'biz_customer/5913364872',
    _rev: '_cfg3ZUy---',
    customer_id: '2',
    customer_name: 'NIKKO',
    customer_kana: 'ニッコウ',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913364873',
    _id: 'biz_customer/5913364873',
    _rev: '_cfg3ZUy--A',
    customer_id: '3',
    customer_name: '三谷',
    customer_kana: 'ミタニ',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913364874',
    _id: 'biz_customer/5913364874',
    _rev: '_cfg3ZUy--C',
    customer_id: '4',
    customer_name: 'CiscoVN',
    customer_kana: '',
    office_zip: '',
    office_tel: '1900585807',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913364875',
    _id: 'biz_customer/5913364875',
    _rev: '_cfg3ZUy--E',
    customer_id: '5',
    customer_name: 'Phong Vu',
    customer_kana: '',
    office_zip: '',
    office_tel: '62908777-111',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913364876',
    _id: 'biz_customer/5913364876',
    _rev: '_cfg3ZUy--G',
    customer_id: '6',
    customer_name: 'HCM郵便局',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913364877',
    _id: 'biz_customer/5913364877',
    _rev: '_cfg3ZU2---',
    customer_id: '7',
    customer_name: 'Smart IT',
    customer_kana: '',
    office_zip: '',
    office_tel: '39434352',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913364878',
    _id: 'biz_customer/5913364878',
    _rev: '_cfg3ZU2--A',
    customer_id: '8',
    customer_name: 'Lemon tree',
    customer_kana: '',
    office_zip: '',
    office_tel: '39102616',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913364879',
    _id: 'biz_customer/5913364879',
    _rev: '_cfg3ZU2--C',
    customer_id: '9',
    customer_name: 'Trung Tam 3',
    customer_kana: '',
    office_zip: '',
    office_tel: '38294274',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913364880',
    _id: 'biz_customer/5913364880',
    _rev: '_cfg3ZU2--E',
    customer_id: '10',
    customer_name: 'ACB',
    customer_kana: '',
    office_zip: '',
    office_tel: '38214619',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365230',
    _id: 'biz_customer/5913365230',
    _rev: '_cfg4yFe---',
    customer_id: '11',
    customer_name: 'SOFTBANKVN',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365231',
    _id: 'biz_customer/5913365231',
    _rev: '_cfg4yFe--A',
    customer_id: '12',
    customer_name: 'Gia Bao',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365232',
    _id: 'biz_customer/5913365232',
    _rev: '_cfg4yFe--C',
    customer_id: '13',
    customer_name: 'VTN1',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365233',
    _id: 'biz_customer/5913365233',
    _rev: '_cfg4yFe--E',
    customer_id: '14',
    customer_name: 'Gia Bao',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365234',
    _id: 'biz_customer/5913365234',
    _rev: '_cfg4yFe--G',
    customer_id: '15',
    customer_name: 'Anh Duong',
    customer_kana: '',
    office_zip: '',
    office_tel: '38235049',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365235',
    _id: 'biz_customer/5913365235',
    _rev: '_cfg4yFe--I',
    customer_id: '16',
    customer_name: 'VJCC',
    customer_kana: 'ＶＪＣＣ',
    office_zip: '',
    office_tel: '08-3512-2151',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365236',
    _id: 'biz_customer/5913365236',
    _rev: '_cfg4yFe--K',
    customer_id: '17',
    customer_name: 'VJCC-HCM',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365237',
    _id: 'biz_customer/5913365237',
    _rev: '_cfg4yFe--M',
    customer_id: '18',
    customer_name: 'BMS VietNam Company Limited',
    customer_kana: '',
    office_zip: '',
    office_tel: '08-3824-5085',
    office_fax: '08-3824-5059',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365238',
    _id: 'biz_customer/5913365238',
    _rev: '_cfg4yFe--O',
    customer_id: '19',
    customer_name: 'Buu Dien',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365239',
    _id: 'biz_customer/5913365239',
    _rev: '_cfg4yFe--Q',
    customer_id: '20',
    customer_name: 'Anh Tuan Dien Thoai',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365240',
    _id: 'biz_customer/5913365240',
    _rev: '_cfg4yFe--S',
    customer_id: '21',
    customer_name: 'AUREOLE IT',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365241',
    _id: 'biz_customer/5913365241',
    _rev: '_cfg4yFi--_',
    customer_id: '22',
    customer_name: 'Vietcombank',
    customer_kana: '',
    office_zip: '',
    office_tel: '38242867',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365242',
    _id: 'biz_customer/5913365242',
    _rev: '_cfg4yFi--B',
    customer_id: '23',
    customer_name: 'AFCP',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365332',
    _id: 'biz_customer/5913365332',
    _rev: '_cfg5NWS---',
    customer_id: '24',
    customer_name: 'Fujitsu Thailand',
    customer_kana: '',
    office_zip: '',
    office_tel: '+66(0)23021500',
    office_fax: '+66(0)23021666',
    office_address: '',
    homepage: 'http://th.fujitsu.com',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913365508',
    _id: 'biz_customer/5913365508',
    _rev: '_cfg6h9O---',
    customer_id: '25',
    customer_name: 'Fujitsu System Business(Thailand) Ltd.',
    customer_kana: '',
    office_zip: '',
    office_tel: '+66(0)23021500',
    office_fax: '+66(0)23021666',
    office_address: '22-23 Fl.Exchange Tower, 388 Sukhumvit Rd.',
    homepage: 'http://th.fujitsu.com',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367064',
    _id: 'biz_customer/5913367064',
    _rev: '_cfhC60u---',
    customer_id: '26',
    customer_name: 'MILBON VIETNAM CO. LTD',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: 'Tang 6, 35 Dong Khoi, phuong Ben Nghe, quan 1, thanh pho Ho Chi Minh',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367309',
    _id: 'biz_customer/5913367309',
    _rev: '_cfhECC----',
    customer_id: '27',
    customer_name: 'Nomura Research Institute Singapore Pte.Ltd.',
    customer_kana: '',
    office_zip: '',
    office_tel: '+65-6671-9812',
    office_fax: '+65-6671-9828',
    office_address: '10 Marina Boulevard, Marina Bay Financial Centre Tower 2, #33-02, Singapore',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367310',
    _id: 'biz_customer/5913367310',
    _rev: '_cfhECC---A',
    customer_id: '28',
    customer_name: 'SPACE CHART INC.',
    customer_kana: '',
    office_zip: '',
    office_tel: '06-6441-4330',
    office_fax: '06-6441-4530',
    office_address: '3rd floor, Nishisenba Tatsumi bldg.',
    homepage: 'http://www.spacechart.co.jp',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367311',
    _id: 'biz_customer/5913367311',
    _rev: '_cfhECC---C',
    customer_id: '29',
    customer_name: 'FASTEPS CO. LTD.',
    customer_kana: '株式会社 ファステップス',
    office_zip: '',
    office_tel: '03-5360-8998',
    office_fax: '03-5360-8991',
    office_address: '4-32-4 Yotsuya, Shinjyuku-ku',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367312',
    _id: 'biz_customer/5913367312',
    _rev: '_cfhECC---E',
    customer_id: '30',
    customer_name: 'Toyo Business Engineering Corp.',
    customer_kana: '東洋ビジネスエンジニアリング株式会社',
    office_zip: '',
    office_tel: '03-3510-1616',
    office_fax: '03-3510-1627',
    office_address: '20th Floor, KDDI Ootemachi Building 1-8-1 Oote-machi, Chiyoda-ku',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367313',
    _id: 'biz_customer/5913367313',
    _rev: '_cfhECCC--_',
    customer_id: '31',
    customer_name: 'SpaceChart',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367314',
    _id: 'biz_customer/5913367314',
    _rev: '_cfhECCC--B',
    customer_id: '32',
    customer_name: 'CHUUBU KOGYOU VIETNAM CO. LTD.',
    customer_kana: 'チュウブコウギョウベトナム',
    office_zip: '',
    office_tel: '+84-650-222-0492',
    office_fax: '+84-650-222-0491',
    office_address: 'Lot B_4B2_CN, NE5B & DE4 Raod, My Phuoc 3 IZ',
    homepage: 'http://www.chk.co.jp/',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367315',
    _id: 'biz_customer/5913367315',
    _rev: '_cfhECCC--D',
    customer_id: '33',
    customer_name: '山一ハガネ',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367316',
    _id: 'biz_customer/5913367316',
    _rev: '_cfhECCC--F',
    customer_id: '34',
    customer_name: 'IDEMITSU',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367317',
    _id: 'biz_customer/5913367317',
    _rev: '_cfhECCC--H',
    customer_id: '35',
    customer_name: 'SATO VIETNAM SOLUTIONS CO. LTD.',
    customer_kana: '',
    office_zip: '84',
    office_tel: '08-3910-1350',
    office_fax: '08-3910-1352',
    office_address: '6th Floor, Saigon Finance Center 9 Dinh Tien Hoang Street, District 1',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367318',
    _id: 'biz_customer/5913367318',
    _rev: '_cfhECCC--J',
    customer_id: '36',
    customer_name: 'Aureole unit-Devices Manufacturing Service Inc. ',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367319',
    _id: 'biz_customer/5913367319',
    _rev: '_cfhECCC--L',
    customer_id: '37',
    customer_name: '株式会社日立ソリューションズ',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367320',
    _id: 'biz_customer/5913367320',
    _rev: '_cfhECCC--N',
    customer_id: '38',
    customer_name: 'AIPHONE VIETNAM',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367321',
    _id: 'biz_customer/5913367321',
    _rev: '_cfhECCC--P',
    customer_id: '39',
    customer_name: 'KING JIM (VIETNAM) CO. LTD.',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367322',
    _id: 'biz_customer/5913367322',
    _rev: '_cfhECCC--R',
    customer_id: '40',
    customer_name: 'BELMONT MANUFACTURING CO. LTD.',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367323',
    _id: 'biz_customer/5913367323',
    _rev: '_cfhECCC--T',
    customer_id: '41',
    customer_name: 'NEC Vietnam',
    customer_kana: 'NEC Vietnam',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367324',
    _id: 'biz_customer/5913367324',
    _rev: '_cfhECCC--V',
    customer_id: '42',
    customer_name: 'Findgate',
    customer_kana: 'Findgate',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367325',
    _id: 'biz_customer/5913367325',
    _rev: '_cfhECCC--X',
    customer_id: '43',
    customer_name: 'Test',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367865',
    _id: 'biz_customer/5913367865',
    _rev: '_cfhG3gC---',
    customer_id: '44',
    customer_name: 'AUREOLE INFORMATION TECHNOLOGY INC.',
    customer_kana: 'オレオル　インフォメーション　テクノロジー',
    office_zip: '',
    office_tel: '91-3105',
    office_fax: '',
    office_address: '',
    homepage: 'http://www.aureole.vn/ait/japanese/index.html',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367866',
    _id: 'biz_customer/5913367866',
    _rev: '_cfhG3gC--A',
    customer_id: '45',
    customer_name: 'TOMOE VN',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367867',
    _id: 'biz_customer/5913367867',
    _rev: '_cfhG3gC--C',
    customer_id: '46',
    customer_name: 'VECTZ',
    customer_kana: 'VECTZ',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367868',
    _id: 'biz_customer/5913367868',
    _rev: '_cfhG3gC--E',
    customer_id: '47',
    customer_name: 'Fujinet',
    customer_kana: '',
    office_zip: '',
    office_tel: '38227277-817',
    office_fax: '',
    office_address: '',
    homepage: 'http://www.fujinet.net',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367869',
    _id: 'biz_customer/5913367869',
    _rev: '_cfhG3gC--G',
    customer_id: '48',
    customer_name: 'FPT',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: 'http://webmail.fpt.net',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367870',
    _id: 'biz_customer/5913367870',
    _rev: '_cfhG3gC--I',
    customer_id: '49',
    customer_name: 'IMLV',
    customer_kana: '',
    office_zip: '',
    office_tel: '38242651',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367871',
    _id: 'biz_customer/5913367871',
    _rev: '_cfhG3gG---',
    customer_id: '50',
    customer_name: 'VDC',
    customer_kana: '',
    office_zip: '',
    office_tel: '38248888',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367872',
    _id: 'biz_customer/5913367872',
    _rev: '_cfhG3gG--A',
    customer_id: '51',
    customer_name: 'VTN',
    customer_kana: '',
    office_zip: '',
    office_tel: '38815542',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367873',
    _id: 'biz_customer/5913367873',
    _rev: '_cfhG3gG--C',
    customer_id: '52',
    customer_name: 'EVN Telecom',
    customer_kana: '',
    office_zip: '',
    office_tel: '32100313',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367874',
    _id: 'biz_customer/5913367874',
    _rev: '_cfhG3gG--E',
    customer_id: '53',
    customer_name: 'Lac Viet',
    customer_kana: '',
    office_zip: '',
    office_tel: '38423333-144',
    office_fax: '',
    office_address: '',
    homepage: 'http://www.lacviet.com.vn',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367875',
    _id: 'biz_customer/5913367875',
    _rev: '_cfhG3gG--G',
    customer_id: '54',
    customer_name: 'AIT (Aureole Information Technology)',
    customer_kana: '',
    office_zip: '84',
    office_tel: '0982-003-096',
    office_fax: '',
    office_address: '264M Le Van Sy Str, 14 Ward, District 1, Ho Chi Minh City',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367876',
    _id: 'biz_customer/5913367876',
    _rev: '_cfhG3gG--I',
    customer_id: '55',
    customer_name: 'Athena',
    customer_kana: '',
    office_zip: '',
    office_tel: '38244041',
    office_fax: '3910 5735',
    office_address: '',
    homepage: 'http://www.athena.edu.vn',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367877',
    _id: 'biz_customer/5913367877',
    _rev: '_cfhG3gG--K',
    customer_id: '56',
    customer_name: 'SaigonCTT',
    customer_kana: '',
    office_zip: '',
    office_tel: '39338888',
    office_fax: '39321186',
    office_address: '287B Dien Bien Phu Street, District 3',
    homepage: 'http://www.saigonctt.com.vn',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367878',
    _id: 'biz_customer/5913367878',
    _rev: '_cfhG3gG--M',
    customer_id: '57',
    customer_name: 'VNN',
    customer_kana: '',
    office_zip: '',
    office_tel: '119',
    office_fax: '',
    office_address: '',
    homepage: 'http://user.vnn.vn',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367879',
    _id: 'biz_customer/5913367879',
    _rev: '_cfhG3gG--O',
    customer_id: '58',
    customer_name: 'AFAQ',
    customer_kana: '',
    office_zip: '',
    office_tel: '38227200',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367880',
    _id: 'biz_customer/5913367880',
    _rev: '_cfhG3gG--Q',
    customer_id: '59',
    customer_name: 'INFO',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: 'http://sg.infor.com/inforumsg',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367881',
    _id: 'biz_customer/5913367881',
    _rev: '_cfhG3gG--S',
    customer_id: '60',
    customer_name: 'TTTH',
    customer_kana: '',
    office_zip: '',
    office_tel: '38351056',
    office_fax: '',
    office_address: '227 Nguyen Van Cu, Q5',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367882',
    _id: 'biz_customer/5913367882',
    _rev: '_cfhG3gG--U',
    customer_id: '61',
    customer_name: 'APEX VietNam',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367883',
    _id: 'biz_customer/5913367883',
    _rev: '_cfhG3gG--W',
    customer_id: '62',
    customer_name: 'Aureole Construction Software Development Inc.',
    customer_kana: '',
    office_zip: '',
    office_tel: '38219383',
    office_fax: '',
    office_address: '19th FLOOR, Sun Wah Tower',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367884',
    _id: 'biz_customer/5913367884',
    _rev: '_cfhG3gG--Y',
    customer_id: '63',
    customer_name: 'AUREOLE BUSINESS COMPONENTS & DEVICES INC.',
    customer_kana: '',
    office_zip: '',
    office_tel: '0613991015',
    office_fax: '',
    office_address: 'Long Binh Techno Park-EPZ Bien Hoa City-Dong Nai Province',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367885',
    _id: 'biz_customer/5913367885',
    _rev: '_cfhG3gG--a',
    customer_id: '64',
    customer_name: 'ACSD Hanoi',
    customer_kana: '',
    office_zip: '',
    office_tel: '0904128773',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367886',
    _id: 'biz_customer/5913367886',
    _rev: '_cfhG3gK---',
    customer_id: '65',
    customer_name: 'D-Circle',
    customer_kana: '',
    office_zip: '',
    office_tel: '834533',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367887',
    _id: 'biz_customer/5913367887',
    _rev: '_cfhG3gK--A',
    customer_id: '66',
    customer_name: 'AUREOLE I.T. JAPAN BRANCH',
    customer_kana: '',
    office_zip: '',
    office_tel: '81-3-5551-0321',
    office_fax: '81-3-5551-0329',
    office_address: '6-19-20, Tsukiji, Chuo-ku, Tokyo',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367888',
    _id: 'biz_customer/5913367888',
    _rev: '_cfhG3gK--C',
    customer_id: '67',
    customer_name: 'AUREOLE MITANI CHEMICAL & ENVIRONMENT INC．',
    customer_kana: '',
    office_zip: '',
    office_tel: '0613892222',
    office_fax: '',
    office_address: 'Long Binh Techno Park-IZ Bien Hoa City-Dong Nai Province',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367889',
    _id: 'biz_customer/5913367889',
    _rev: '_cfhG3gK--E',
    customer_id: '68',
    customer_name: 'MITANI SANGYO CO. LTD.',
    customer_kana: '',
    office_zip: '',
    office_tel: '81-76-233-2982',
    office_fax: '81-76-233-2879',
    office_address: '1-5 Tamagawa-cho, Kanazawa-shi, Ishikawa-ken, 920-8685, JAPAN',
    homepage: 'http://www.mitani.com',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367890',
    _id: 'biz_customer/5913367890',
    _rev: '_cfhG3gK--G',
    customer_id: '69',
    customer_name: 'NPN',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367891',
    _id: 'biz_customer/5913367891',
    _rev: '_cfhG3gK--I',
    customer_id: '70',
    customer_name: 'ABCD Hai Duong',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367892',
    _id: 'biz_customer/5913367892',
    _rev: '_cfhG3gK--K',
    customer_id: '71',
    customer_name: 'VTN Hanoi',
    customer_kana: '',
    office_zip: '',
    office_tel: '0438344094',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367893',
    _id: 'biz_customer/5913367893',
    _rev: '_cfhG3gK--M',
    customer_id: '72',
    customer_name: 'UPS',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367894',
    _id: 'biz_customer/5913367894',
    _rev: '_cfhG3gK--O',
    customer_id: '73',
    customer_name: 'Fujitsu',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367895',
    _id: 'biz_customer/5913367895',
    _rev: '_cfhG3gK--Q',
    customer_id: '74',
    customer_name: 'TNH',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367896',
    _id: 'biz_customer/5913367896',
    _rev: '_cfhG3gK--S',
    customer_id: '75',
    customer_name: 'DTV',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367897',
    _id: 'biz_customer/5913367897',
    _rev: '_cfhG3gK--U',
    customer_id: '76',
    customer_name: 'MicroSoftVN',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367898',
    _id: 'biz_customer/5913367898',
    _rev: '_cfhG3gK--W',
    customer_id: '77',
    customer_name: 'OracleVN',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367899',
    _id: 'biz_customer/5913367899',
    _rev: '_cfhG3gK--Y',
    customer_id: '78',
    customer_name: 'Phong Vu',
    customer_kana: '',
    office_zip: '',
    office_tel: '9330762',
    office_fax: '9330765',
    office_address: '264C Nguyen Thi Minh Khai Quan 3, TPHCM',
    homepage: 'http://www.vitinhphongvu.com/',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367900',
    _id: 'biz_customer/5913367900',
    _rev: '_cfhG3gK--a',
    customer_id: '79',
    customer_name: 'IMBVN',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367901',
    _id: 'biz_customer/5913367901',
    _rev: '_cfhG3gK--c',
    customer_id: '80',
    customer_name: 'MISOFT',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: 'http://www.misoft.com.vn',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367902',
    _id: 'biz_customer/5913367902',
    _rev: '_cfhG3gK--e',
    customer_id: '81',
    customer_name: 'REP-Mitani-HCM',
    customer_kana: '',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367903',
    _id: 'biz_customer/5913367903',
    _rev: '_cfhG3gO---',
    customer_id: '82',
    customer_name: 'D-Circle',
    customer_kana: 'ディサークル',
    office_zip: '',
    office_tel: '81-3-5551-0321',
    office_fax: '81-3-5551-0329',
    office_address: '6-19-20, Tsukiji, Chuo-ku, Tokyo',
    homepage: 'https://tech.d-circle.com/pe4j-v2/report/10',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367904',
    _id: 'biz_customer/5913367904',
    _rev: '_cfhG3gO--A',
    customer_id: '83',
    customer_name: 'Energia Com',
    customer_kana: 'エネルギーアコン',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  },
  {
    _key: '5913367905',
    _id: 'biz_customer/5913367905',
    _rev: '_cfhG3gO--C',
    customer_id: '84',
    customer_name: 'PREASE',
    customer_kana: 'プリーズ',
    office_zip: '',
    office_tel: '',
    office_fax: '',
    office_address: '',
    homepage: '',
    lastupdate: '',
    remark: ''
  }
]
